name: matching-logic
version: 0.0.1.0
github: "kframework/kore"
license: OtherLicense
license-file: LICENSE
author: "Brandon Moore"
maintainer: "brandon.moore@runtimeverification.com"
copyright: "2018 Runtime Verification Inc"
category: Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/kframework/kore/blob/master/src/main/haskell/language-kore/README.md>

extra-source-files:
  - README.md
  - ChangeLog.md
  - test/resources/**

dependencies:
  - base >=4.7 && <5
  - containers
  - data-fix
  - deriving-compat
  - free
  - haskeline
  - language-kore
  - lens
  - megaparsec
  - mtl
  - prettyprinter
  - recursion-schemes
  - reflection
  - text

library:
  source-dirs: src
  exposed-modules:
    - Kore.MatchingLogic.AST
    - Kore.MatchingLogic.AST.Syntax
    - Kore.MatchingLogic.Error
    - Kore.MatchingLogic.HilbertProof
    - Kore.MatchingLogic.ProofSystem.Dummy
    - Kore.MatchingLogic.ProofSystem.Minimal
    - Kore.MatchingLogic.ProofSystem.Minimal.Syntax
    - Kore.MatchingLogic.ProofSystem.MLProofSystem
    - Kore.MatchingLogic.ProverRepl
    - Kore.MatchingLogic.Signature
    - Kore.MatchingLogic.Signature.Simple
    - Kore.MatchingLogic.Signature.Poly
  default-extensions:
    - DataKinds
    - DeriveFoldable
    - DeriveFunctor
    - DeriveTraversable
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - MultiParamTypeClasses
    - RankNTypes
    - ScopedTypeVariables
    - StandaloneDeriving
    - TypeSynonymInstances
    - UndecidableInstances

executables:
  prover:
    source-dirs: app
    main: Main.hs
    default-extensions:
      - FlexibleContexts
    dependencies:
      - matching-logic

tests:
  test:
    source-dirs: test
    main: AllTests.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    default-extensions:
      - DataKinds
      - DeriveFoldable
      - DeriveFunctor
      - DeriveTraversable
      - FlexibleContexts
      - FlexibleInstances
      - FunctionalDependencies
      - MultiParamTypeClasses
      - RankNTypes
      - ScopedTypeVariables
      - StandaloneDeriving
      - TypeSynonymInstances
      - UndecidableInstances
    dependencies:
      - language-kore
      - matching-logic
      - bytestring
      - directory >= 1.2.2
      - filepath
      - QuickCheck
      - tasty
      - tasty-ant-xml
      - tasty-golden
      - tasty-hunit
      - tasty-quickcheck
      - template-haskell
