name: 'Materialize'
on:
  push:
    branches-ignore:
      - 'master'
jobs:
  release:
    name: 'Materialize'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          extra_nix_config: |
            substituters = http://cache.nixos.org https://hydra.iohk.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - name: Install Cachix
        uses: cachix/cachix-action@v8
        with:
          name: runtimeverification
          extraPullNames: 'kore'
          skipPush: true

      - name: Materialize
        run: ./nix/rematerialize.sh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: 'Materialize Nix expressions'
          file_pattern: 'nix/'
