name: "Performance"
on:
  pull_request:
jobs:
  performance:
    name: 'Performance'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          # Check out pull request HEAD instead of merge commit.
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          extra_nix_config: |
            substituters = http://cache.nixos.org https://hydra.iohk.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - name: Install Cachix
        uses: cachix/cachix-action@v8
        with:
          name: kore
          extraPullNames: runtimeverification
          signingKey: '${{ secrets.KORE_CACHIX_SIGNING_KEY }}'
          skipPush: true

      - name: Build
        run: |
          ./scripts/test-statistics.sh ./. test/regression-evm >pull-request.json
          git fetch origin
          git worktree add kore-master master
          ./scripts/test-statistics.sh ./kore-master test/regression-evm >master.json
          ./scripts/join-statistics.sh master.json pull-request.json
