name: 'Update'
on:
  push:
    branches-ignore:
      - 'master'
  pull_request:
jobs:
  nix:
    name: 'Nix'
    runs-on: ubuntu-latest
    steps:
      - id: config
        run: |
          if [ "${{ github.event_name }}" == 'pull_request' ]
          then
            echo "::set-output name=ref::${{ github.event.pull_request.head.sha }}"
          else
            echo "::set-output name=ref::$GITHUB_SHA"
          fi

      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ steps.config.outputs.ref }}
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          extra_nix_config: |
            substituters = http://cache.nixos.org https://hydra.iohk.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - name: Install Cachix
        uses: cachix/cachix-action@v8
        with:
          name: kore
          signingKey: '${{ secrets.KORE_CACHIX_SIGNING_KEY }}'

      - name: Materialize
        run: ./nix/rematerialize.sh

      - name: Update branch
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            if [ -n "$(git status --porcelain '*.hs')" ]; then
              git diff
              exit 1
            fi
          fi
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add '*.hs'
          git commit -m 'Materialize Nix expressions'
          git push

  fourmolu:
    name: 'Style'
    runs-on: ubuntu-latest
    steps:
      - id: config
        run: |
          if [ "${{ github.event_name }}" == 'pull_request' ]
          then
            echo "::set-output name=ref::${{ github.event.pull_request.head.sha }}"
          else
            echo "::set-output name=ref::$GITHUB_SHA"
          fi

      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ steps.config.outputs.ref }}
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          extra_nix_config: |
            substituters = http://cache.nixos.org https://hydra.iohk.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - name: Install Cachix
        uses: cachix/cachix-action@v8
        with:
          name: kore
          signingKey: '${{ secrets.KORE_CACHIX_SIGNING_KEY }}'

      - name: Format
        run: ./nix/fourmolu.sh

      - name: Check for changes
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if [ ! $(git status --porcelain | wc -l) -eq 0 ]; then
            git diff
            exit 1
          fi

      - name: Update branch
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            if [ -n "$(git status --porcelain '*.hs')" ]; then
              git diff
              exit 1
            fi
          fi
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add '*.hs'
          git commit -m 'Format with fourmolu'
          git push
