name: 'Update'
on:
  push:
    branches-ignore:
      - 'master'
  pull_request:
jobs:
  nix:
    name: 'Nix'
    runs-on: ubuntu-latest
    steps:
      - id: config
        run: |
          if [ "${{ github.event_name }}" == 'pull_request' ]
          then
            echo "::set-output name=ref::${{ github.event.pull_request.head.sha }}"
          else
            echo "::set-output name=ref::$GITHUB_SHA"
          fi

          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ steps.config.outputs.ref }}
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          extra_nix_config: |
            substituters = http://cache.nixos.org https://hydra.iohk.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - name: Install Cachix
        uses: cachix/cachix-action@v8
        with:
          name: kore
          signingKey: '${{ secrets.KORE_CACHIX_SIGNING_KEY }}'

      - name: Materialize
        run: ./nix/rematerialize.sh

      - name: Update branch
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: |
          if [ -n "$(git status --porcelain 'nix/')" ]; then
            if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
              echo 2>&1 "Error: found modified files"
              git diff
              exit 1
            elif [[ $GITHUB_EVENT_NAME == 'push' ]]; then
              git add 'nix/'
              git commit -m 'Materialize Nix expressions'
              git push
            else
              echo 2>&1 "Error: event not supported: $GITHUB_EVENT_NAME"
            fi
          fi

  fourmolu:
    name: 'Style'
    runs-on: ubuntu-latest
    steps:
      - id: config
        run: |
          if [ "${{ github.event_name }}" == 'pull_request' ]
          then
            echo "::set-output name=ref::${{ github.event.pull_request.head.sha }}"
          else
            echo "::set-output name=ref::$GITHUB_SHA"
          fi

          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ steps.config.outputs.ref }}
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          extra_nix_config: |
            substituters = http://cache.nixos.org https://hydra.iohk.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - name: Install Cachix
        uses: cachix/cachix-action@v8
        with:
          name: kore
          signingKey: '${{ secrets.KORE_CACHIX_SIGNING_KEY }}'

      - name: Format
        run: ./nix/fourmolu.sh

      - name: Update branch
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: |
          if [ -n "$(git status --porcelain '*.hs')" ]; then
            if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
              echo 2>&1 "Error: found modified files"
              git diff
              exit 1
            elif [[ $GITHUB_EVENT_NAME == 'push' ]]; then
              git add '*.hs'
              git commit -m 'Format with fourmolu'
              git push
            else
              echo 2>&1 "Error: event not supported: $GITHUB_EVENT_NAME"
            fi
          fi
